name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: .github/scripts/install-debian-deps.sh

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: .github/scripts/install-macos-deps.sh

    - name: Install Windows Dependencies
      if: runner.os == 'Windows'
      run: .github\scripts\install-windows-deps.ps1

    - name: Setup [Unix]
      if: runner.os != 'Windows'
      run: meson setup build

    - name: Setup [Windows]
      if: runner.os == 'Windows'
      run: |
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv
        meson setup build

    - name: Compile
      run: meson compile -C build

    - name: Save Build Log Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: meson-build-log-${{ runner.os }}.txt
        path: build/meson-logs/meson-log.txt
