name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: .github/scripts/install-debian-deps.sh

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: .github/scripts/install-macos-deps.sh

    - name: Setup
      run: meson setup build

    - name: Compile
      run: meson compile -C build

    - name: Print meson log
      if: ${{ always() }}
      run: cat build/meson-logs/meson-log.txt
